# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .vscode\vs_requirements.txt
    - name: Install pyproject
      run: |
        pip install -e .
    - name: Check import order with isort
      run: |
        isort .
    - name: Check formatting with black
      run: |
        black --check .
    - name: Check formatting with flake8 [flake-bugbear & flake8-docstrings]
      run: |
        flake8 .
    - name: Test with pytest & pytest-cov
      run: |
        pytest --cov
